# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Windows - .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    # OS Supported: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, windows-2016]
        dotnet: [ '3.1.x', '5.0.x' ]

    name: .NET Core ${{ matrix.dotnet }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Upload a Shared Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Shared-Package
          path: ${{github.workspace}}/src/Shared/bin/Debug/netcoreapp3.1/
      - name: Upload a HGWC Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: HGWC-Package
          path: ${{github.workspace}}/src/HGWC/bin/Debug/netcoreapp3.1/
      - name: Upload a Login Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Login-Package
          path: ${{github.workspace}}/src/Login/bin/Debug/netcoreapp3.1/
      - name: Upload a Game Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Game-Package
          path: ${{github.workspace}}/src/Game/bin/Debug/netcoreapp3.1/